### ISSUE TITLE
Code review first iteration

### ISSUE THREAD

**Issue by pavelchadnov** [yeputons/ofeed#1]
First iteration of the code review. Please address these comments:
- First of all, it's not clear for me how to build/run. I was able to run it on a physical Android device but still have no idea how to build/run from source; For example I do not know what version of OrmLite should be used (I tried to use the latest one from maven; apparently you used a different one as code doesn't compile)
- Please use single naming convention. Sometimes you_use_underscores (VKApiFeedPage, VKApiFeedItem, etc) and sometimes camelCase.
- Please be consistent about your creation of TAG used for logging in every class. Sometimes it's just a hardcoded string; sometimes it is ClassName.class.getName()
- DownloadManagerResourceDownloader.java: 
  static private final String TAG 
  private static final String TAG
- VKApiFeedItem.java: VKApiFeedItem() constructor is unused
- VKApiFeedItem.java: public VKApiFeedItem(JSONObject from) is unused
- DeepWebPageSaver.java: in downloadPageResources method you catch an IOException and do e.printStackTrace(). Why do you print it to stderr instead of using Log.e()?
- FeedListViewAdapter.java: do you really expect number of feed items to be more than Integer.MAX_VALUE?
- DownloadCompleteBroadcastReceiver.java: in onReceive method you call Log.i("TAG", ...). Is that "TAG" really what you want to log?
- ThreadPoolResourceDownloader.java: 
   if (responseCode / 100 != 2) {
  Please extract a method or at least add the comment about what this logic means
- Please remove the commented out code blocks (I guess some of those were used for debugging, so no need to keep them)
- Also you have many imports that are unused, please clean them up
- It would be awesome if there were some unit tests
- There are multiple places where you catch SQLException, log it and just throw the RuntimeException. I would recommend to add some retry logic (if a sql query failed, try do it NUM_RETRIES-1 more times, possibly with some delay and throw the RuntimeException if the query never succeeds)

**Comment by yeputons** [comment]
@pavelchadnov Thank you very much! Fixed almost all of them.
- Added build instructions to README. Command line building is not supported because my project wants Ant and the library used wants Gradle. I think it's possible to make it work by adding Ant script for the library, though.
- Added `checkstyle.xml` for imports and stuff.
- Regarding `FeedListViewAdapter`: I don't expect that, but do you think it'll be better omitting that check (3bb11f117cebe65c11b2fe963125229bff98bc38)? Looks rather scary to me :)
- Regarding `SQLException`: I don't see how instant retrying may theoretically help. SQL database is fully local (sqlite, to be precise) and if it fails, it's probably damaged or there is no free space. Either way, there is little we can do to fix that and attempting one more time probably won't help.
- I'm not sure how something here can be unit tested. Probably, the most dangerous place is feed gluing and in-place loading <a href="https://github.com/yeputons/ofeed/blob/master/src/net/yeputons/ofeed/MainActivity.java#L280-L306">in MainActivity</a>. Looks like I will have to extract that piece of code to a separate method (or even class). Some other dangerous places include `DownloadableImageView`, `PostView` and friends (because they're reused across posts and race conditions are possible between "download complete" and "show another post/picture" events). Another candidate for testing is `DeepWebPageSaver` and friends, but the downloading classes are tightly connected to Android API and I do not see any meaningful "unit" testing, because behavior of each of them is pretty straightforward.

Regarding `com.vk.sdk.api.*` classes and naming conventions: original VK SDK library does not support any feed-related API, that's why I had to implement some `com.vk.sdk.api.*` classes myself (three of them: `VKApiFeed`, `VKApiFeedItem`, `VKApiFeedPage`). These classes follow library's coding conventions, as I understood them: standard Java everywhere, but field names are equal to what's specified in VK's documentation on JSON objects, and they use underscore there. I thought it would be a good idea to file a pull request (or, at the very least, open an issue and attach my source as an "starting" implementation). So, that lead to two decisions:
- Add separate field naming convention to checkstyle for these classes and make sure that they follow underscore convention.
- Follow existing classes design closely, including implementing constructors that I personally don't need.

Nevertheless, I've made that consistent (it was not): camelCase in my classes and underscores in vk classes.

**Comment by pavelchadnov** [comment]
@yeputons 
Thanks for improvements;

Some more minor notes:
- As you mentioned at least DeepWebPageSaver logic that modifies the HTML can be somehow unittested
- SQLException: SQL database can throw due to some transient error (for example bug in DB itself or the Java API you use) and you can possibly make your app more stable if you retry (possibly with some delay)
- Regarding int overflow check in FeedListViewAdapter: you're right, it's scary :) Feel free to revert it or leave it as is (whatever you're comfortable with), sorry for confusion

These are not must-fix, so it's up to you if you're gonna do that (as far as I know you still have couple days to do that before the deadline); overall everything looks good to me

**Comment by yeputons** [comment]
@pavelchadnov Thanks! Unfortunately, I don't think I'll be able to come up with a unit testing in a reasonable amount of time. Does that make it -0.2 or 0.0?

I still can't believe that `SQLException` can be caused by transient error and that it makes sense to retry: have you ever heard or met such situations with local DBs? Both described situations (bug in DB or JVM) looks very unstable for me to even continue running the application - anything can go wrong if there is such kind of bug in external code.
